# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDBmMmI2ODUyMzE5YWJkN2JjNTQ5YTc3Y2YxMmFlZTYxZDIxYzI1Y2EyMjMxZjM0Zjk4NDVkYTFmZjMyYTQxMGViNzhmZjcyYzk1OWNkZjc0MTFmMzZhMWE1NWM1ZWI1ZDY2MDQwMjQzYmI2OGYzOTk3YTg4YTYyNzIyNTIyZmE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
